"""EL DICCIONARI ES MUTABLE, A DIFERENCIAS DE LOS DEMAS, SE DEBEN DE DIFERENCIASR A TRAVEZ DE UN PAR,
LA FORMA DE DEFINIR UN DICCIONARIO ES A TRAVES DE LAS LLAVES JUNTO CON LO QUE ES UN : Y OTRO ELEMENTO, ASI COMO SE PUDE VISUALIZAR EN LA
SIGUIENTE PARTE DEL PROGRAMA.
"""
alumnos = {'Juan':'ISC', 'Mario':'ISC'}
print(alumnos)
print(type(alumnos))





